project:
  type: book

book:
  title: "Foundation Year R Programming"
  author: "Jonathan Binder"
  date: "01/15/2023"
  chapters:
    - index.qmd
    - wk1-intro.qmd
    - wk2-averages-sd-se.qmd
    - wk3-normality.qmd
    - wk4-ggplot1.qmd
    - wk5-ggplot2.qmd
    - wk6-corr-reg.qmd
    - wk7-ttest-wilcoxon.qmd
    - wk8-chisquared-fisherexact.qmd
    - wk9-anova-kruskal-wallis.qmd
    - wk10-post-hoc.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt





